theme: jekyll-theme-minimal
title: Edward Wiles
description: |
  Academy Scholar  
  [Harvard Academy for International and Area Studies](https://academyscholarsprogram.harvard.edu/)  
  Cambridge, MA USA  

[CV](https://edwardwiles.github.io/storage/cv/EdwardWilesCV.pdf) | [Email](mailto:edward.m.wiles@gmail.com)
